#!/bin/bash
sudo apt-get update
sudo apt-get remove mysql-client mysql-community-server mysql-server
sudo sh -c 'echo "deb http://repo.mysql.com/apt/ubuntu bionic mysql-5.7" >> /etc/apt/sources.list.d/mysql.list'
sudo apt install -f mysql-client=5.7.* mysql-community-server=5.7.* mysql-server=5.7.*
